Use tcs log.

diff --git a/tcs/libexec/tcs/fetchblocks b/tcs/libexec/tcs/fetchblocks
--- a/tcs/libexec/tcs/fetchblocks
+++ b/tcs/libexec/tcs/fetchblocks
@@ -10,12 +10,15 @@ usageerror () {
 }
 
 error () {
-  echo 1>&2 "$(date -u '+%F %T'): $program: error: $@"
+  log error "$@"
   exit 1
 }
 
 log () {
-  echo 1>&2 "$(date -u '+%F %T'): $program: $@"
+  level=$1
+  shift
+  tcs log "$program" $level "$*"
+  echo 1>&2 "$(date -u '+%F %T'): $program: $level: $*"
 }
 
 optstring=
@@ -33,14 +36,24 @@ do
   esac
 done
 shift
-if test $# != 1
+if test $# = 0
 then
+  case $(hostname) in
+  coatlioan-*)
+    url="https://github.com/alanwatsonforster/coatlioan-blocks.git"
+    ;;
+  *)
+    error "unable to determing URL."
+    ;;
+  esac
+elif test $# = 1
+then
+  url="$1"
+else
   usageerror
 fi
 
-url="$1"
-
-log "starting."
+log summary "fetching blocks."
 
 ################################################################################
 
@@ -50,7 +63,7 @@ cd "$etcdir"
 
 ################################################################################
 
-log "cloning to blocks.new/."
+log info "cloning from $url to blocks.new/."
 rm -rf blocks.new
 mkdir blocks.new
 if ! git clone -q $url blocks.new/
@@ -60,18 +73,18 @@ fi
 
 ################################################################################
 
-log "moving blocks/ to blocks.old/."
+log info "moving blocks/ to blocks.old/."
 rm -rf blocks.old
 mv blocks blocks.old
 
 ################################################################################
 
-log "moving blocks.new/ to blocks/."
+log info "moving blocks.new/ to blocks/."
 mv blocks.new blocks
 
 ################################################################################
 
-log "finished."
+log summary "finished fetching blocks."
 
 exit 0
 
