Fix sending chat messages.

diff --git a/tcs/libexec/tcs/sendchat b/tcs/libexec/tcs/sendchat
--- a/tcs/libexec/tcs/sendchat
+++ b/tcs/libexec/tcs/sendchat
@@ -110,21 +110,28 @@ fi
 
 #url="https://chat.googleapis.com/v1/spaces/AAAALqR-TN0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=H4Mc4xQFoOAIsTvj0v1l15EwEqPaHY8ZUWgzGoqtQ8M"
 
-case "$url" in
-*mattermost*)
-  if ! curl -s -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$source: $message\"}" $url >/dev/null
-  then
-    echo 2>&1 "$program: error: API call failed."
+for url in $urls
+do
+  case "$url" in
+  *mattermost*)
+    if ! curl -s -X POST -H 'Content-Type: application/json' -d "{\"text\": \"$source: $message\"}" $url >/dev/null
+    then
+      echo 2>&1 "$program: error: API call failed."
+      exit 1
+    fi
+    ;;
+  *googleapis*)
+    if ! curl -s -X POST -H "Content-Type: application/json" -d "{\"text\": \"$source: $message\"}" $url >/dev/null
+    then
+      echo 2>&1 "$program: error: API call failed."
+      exit 1
+    fi
+    ;;
+  *)
+    echo 2>&1 "$program: error: unknown url \"$url\"."
     exit 1
-  fi
-  ;;
-*googleapis*)
-  if ! curl -s -X POST -H "Content-Type: application/json" -d "{\"text\": \"$source: $message\"}" $url >/dev/null
-  then
-    echo 2>&1 "$program: error: API call failed."
-    exit 1
-  fi
-  ;;
-esac
+    ;;
+  esac
+done
 
 exit 0
